twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_horizontal_layout.html.twig'
    globals:
        app_feature: '%env(bool:APP_FEATURE)%'

when@test:
    twig:
        strict_variables: true
